### ISSUE TITLE
Token only lasts a few days

### ISSUE THREAD

**Issue by davisgiles** [chuck-alt-delete/sunpower#1]
Firstly want to say thank you for this repo! Being able to pull data from my sunpower system has been something I’ve wanted to do for a while. 

I’ve forked your repo and have automated collecting hourly interval readings once per day and it works perfectly. Each day I am only collecting the previous 24 hours in one request. However the token expires after a couple of days and only 2-3 uses with the token. Is there anything I can do to extend the use of a token? 

Appreciate the help!

**Comment by chuck-alt-delete** [comment]
Nice, I’ll take a look!

For security reasons, they have to set an expiry on the token. Usually in situations like these, they would make the API public and you could get a long-lived API key, but unfortunately this is a private API.

**Comment by chuck-alt-delete** [comment]
Could you provide a link to your fork? I can’t find it easily
